import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import AuthProvider from '@/components/AuthProvider'
import './globals.css'
// import "bootstrap"
import 'bootstrap/dist/css/bootstrap.min.css'
import 'react-toastify/dist/ReactToastify.css'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E voting',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang='en'>
        <body className={inter.className}>
          {children}
          <ToastContainer />
        </body>
      </html>
    </AuthProvider>
  )
}
